CREATE TABLE PIED_PIPER_REFERRAL_LINKS
(
    LINK_ID    VARCHAR2(2000) PRIMARY KEY,
    REFERER_ID VARCHAR2(500),
    ACTIVATED  CHAR(1),
    FOREIGN KEY (REFERER_ID) REFERENCES PIED_PIPER_USER (USER_ID) ON DELETE SET NULL
)