CREATE TABLE PIED_PIPER_QUESTIONS
(
    QUESTION_ID   VARCHAR2(100) PRIMARY KEY,
    QUESTION_TYPE VARCHAR2(100) NOT NULL,
    IS_IMMUTABLE  CHAR(1) NOT NULL,
    CONTENT       VARCHAR2(100) NOT NULL
)
