CREATE TABLE PIED_PIPER_USER
(
    USER_ID        VARCHAR2(100) PRIMARY KEY,
    LOGIN_VALUE    VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD_VALUE VARCHAR2(100) NOT NULL,
    USER_NAME       VARCHAR2(100),
    USER_SURNAME    VARCHAR2(100),
    USER_PATRONYMIC VARCHAR2(100),
    USER_ROLE_TYPE  VARCHAR2(100)
)