CREATE TABLE PIED_PIPER_REFERRAL_LINKS
(
    LINK_ID    VARCHAR2(500) PRIMARY KEY,
    REFERER_ID VARCHAR2(100),
    ACTIVATED  CHAR(1),
    FOREIGN KEY (REFERER_ID) REFERENCES PIED_PIPER_USER (USER_ID)
)