CREATE TABLE PIED_PIPER_CANDIDATE
(
    CANDIDATE_ID VARCHAR2(100) PRIMARY KEY,
    REFERER_ID   VARCHAR2(100),
    APPROVED     CHAR(1),
    FORM         VARCHAR2(5000),
    FOREIGN KEY (REFERER_ID) REFERENCES PIED_PIPER_USER (USER_ID) ON DELETE SET NULL
)