CREATE SEQUENCE dept_seq START WITH 1;

CREATE TABLE PIED_PIPER_QUESTIONS_NEW
(
    QUESTION_ID   NUMBER PRIMARY KEY ,
    QUESTION_TYPE VARCHAR2(100)  NOT NULL,
    IS_IMMUTABLE  CHAR(1)        NOT NULL,
    CONTENT       VARCHAR2(2000) NOT NULL,
    IS_ACTIVE     CHAR(1)        NOT NULL
);

CREATE OR REPLACE TRIGGER dept_bir
    BEFORE INSERT ON PIED_PIPER_QUESTIONS_NEW
    FOR EACH ROW

BEGIN
    SELECT dept_seq.NEXTVAL
    INTO   :new.QUESTION_ID
    FROM   dual;
END;
/
